package com.lnsoft.mapper;

import com.lnsoft.dataobject.PromoInfoDo;
import com.lnsoft.dataobject.PromoInfoDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromoInfoDoMapper {

    PromoInfoDo selectByItemId(@Param("itemId") Integer itemId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    long countByExample(PromoInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    int deleteByExample(PromoInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    int insert(PromoInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    int insertSelective(PromoInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    List<PromoInfoDo> selectByExample(PromoInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    PromoInfoDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") PromoInfoDo record, @Param("example") PromoInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    int updateByExample(@Param("record") PromoInfoDo record, @Param("example") PromoInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    int updateByPrimaryKeySelective(PromoInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 09 16:14:35 CST 2019
     */
    int updateByPrimaryKey(PromoInfoDo record);
}