package com.lnsoft.mapper;

import com.lnsoft.dataobject.SequenceInfoDo;
import com.lnsoft.dataobject.SequenceInfoDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceInfoDoMapper {

    SequenceInfoDo getSequenceByName(@Param("sequenceName") String sequenceName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    long countByExample(SequenceInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    int deleteByExample(SequenceInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    int deleteByPrimaryKey(String sequenceName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    int insert(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    int insertSelective(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    List<SequenceInfoDo> selectByExample(SequenceInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    SequenceInfoDo selectByPrimaryKey(String sequenceName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") SequenceInfoDo record, @Param("example") SequenceInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    int updateByExample(@Param("record") SequenceInfoDo record, @Param("example") SequenceInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    int updateByPrimaryKey(SequenceInfoDo record);
}