package com.lnsoft.mapper;

import com.lnsoft.dataobject.UserInfoDO;
import com.lnsoft.dataobject.UserInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    long countByExample(UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    int deleteByExample(UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    int insert(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    int insertSelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    List<UserInfoDO> selectByExample(UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    UserInfoDO selectByPrimaryKey(Integer id);

    UserInfoDO selectByTelPhone(String telPhone);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserInfoDO record, @Param("example") UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    int updateByExample(@Param("record") UserInfoDO record, @Param("example") UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    int updateByPrimaryKeySelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Dec 30 11:02:23 CST 2018
     */
    int updateByPrimaryKey(UserInfoDO record);
}