package com.lnsoft.dataobject;

public class SequenceInfoDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.sequence_name
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    private String sequenceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.current_value
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    private Integer step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.max_value
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    private Integer maxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.init_value
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    private Integer initValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.sequence_name
     *
     * @return the value of sequence_info.sequence_name
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public String getSequenceName() {
        return sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.sequence_name
     *
     * @param sequenceName the value for sequence_info.sequence_name
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public void setSequenceName(String sequenceName) {
        this.sequenceName = sequenceName == null ? null : sequenceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.current_value
     *
     * @return the value of sequence_info.current_value
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.current_value
     *
     * @param currentValue the value for sequence_info.current_value
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.max_value
     *
     * @return the value of sequence_info.max_value
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public Integer getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.max_value
     *
     * @param maxValue the value for sequence_info.max_value
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public void setMaxValue(Integer maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.init_value
     *
     * @return the value of sequence_info.init_value
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public Integer getInitValue() {
        return initValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.init_value
     *
     * @param initValue the value for sequence_info.init_value
     *
     * @mbg.generated Mon Jan 07 22:03:09 CST 2019
     */
    public void setInitValue(Integer initValue) {
        this.initValue = initValue;
    }
}